import { Types } from "mongoose";

export interface IAuth {
  email: string;
  password: string;
}
// Generated by https://quicktype.io

export interface IAuthGoogle {
  googleUser: GoogleUser;
}

export interface GoogleUser {
  name: string;
  picture: string;
  email: string;
}

export interface ICode {
  userId: Types.ObjectId;
  code: string;
  createdAt: Date;
  expiresAt: Date;
}
