export interface IAuth {
    email: string;
    password: string;
}
// Generated by https://quicktype.io

export interface IAuthGoogle {
    googleUser: GoogleUser;
}

export interface GoogleUser {
    name: string;
    picture: string;
    email: string;
}

